import React, { Component } from 'react';
import PropTypes from 'prop-types';
import TextareaAutosize from 'react-textarea-autosize';
import moment from 'moment';
import Tooltip from '../Tooltip';

export default class InputFilename extends Component {
  handleChange = e => {
    const { onChange } = this.props;
    onChange(e.target.value);
  };

  render() {
    const { path, type } = this.props;
    const date = moment().format('YYYY-MM-DD');
    const placeholder = `${date}-your-title.md`;

    const tooltipText = (
      <span>
        Posts are required to have a <b>filename</b>. Path is the{' '}
        <b>name and location</b> of the file in the site's source directory. If
        you leave path blank, it will be <b>autogenerated from title</b>.
      </span>
    );

    return (
      <div className="input-path">
        <label>
          Path
          <Tooltip content={tooltipText} />
        </label>
        <TextareaAutosize
          key={path}
          onChange={this.handleChange}
          placeholder={placeholder}
          defaultValue={path}
          ref="input"
        />
      </div>
    );
  }
}

InputFilename.propTypes = {
  path: PropTypes.string.isRequired,
  type: PropTypes.string.isRequired,
  onChange: PropTypes.func.isRequired,
};
